name: Qt-GammaRay Builds
on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  GammaRay-x64:
    runs-on: windows-2019
    env:
      CI_QT_VERSION: 5.15.2
      IDA_VERSION: 8.4
      CI_SEED: 1234567891  # cache buster
      GITHUB_WORKSPACE: ${{ github.workspace }}
    steps:
      - name: Enable Developer Command Prompt (Windows)
        uses: ilammy/msvc-dev-cmd@v1.12.1
        with:
            # 14.1 is for vs2017, 14.2 is vs2019, omit key for latest
            toolset: 14.2
            sdk: "10.0.19041.0"
            arch: amd64
      - name: Install jom
        shell: powershell
        run: |
          Set-Location C:\
          Invoke-WebRequest 'http://download.qt.io/official_releases/jom/jom.zip' -OutFile .\jom.zip
          Expand-Archive .\jom.zip
          Remove-Item .\jom.zip
          Get-ChildItem $(pwd)
          Get-ChildItem .\jom
          Get-PSDrive
      - name: Check MSBuild and Qt
        run: |
          msbuild -version | Out-File -FilePath "$env:GITHUB_WORKSPACE\msbuild_version"
          Get-Content -Path "$env:GITHUB_WORKSPACE\msbuild_version"
          $env:CI_QT_VERSION | Out-File -FilePath "$env:GITHUB_WORKSPACE\qt_version"
          $env:CI_SEED | Out-File -FilePath "$env:GITHUB_WORKSPACE\cache_seed"
      - name: Restore Qt cache
        id: qt-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ github.job }}-qt-${{ hashFiles('msbuild_version', 'qt_version', 'cache_seed') }}
      - name: Clone Qt ${{ env.CI_QT_VERSION }}
        if: steps.qt-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: qt/qt5
          ref: v${{ env.CI_QT_VERSION }}
          fetch-depth: 1
          submodules: recursive
          path: ${{ github.workspace }}/Qt
      - name: Build Qt ${{ env.CI_QT_VERSION }}
        # if: steps.qt-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          @echo on
          echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
          set _QT_BUILD_ROOT=%GITHUB_WORKSPACE%\Qt\build\${{ env.CI_QT_VERSION }}
          mkdir %_QT_BUILD_ROOT%\
          mkdir %_QT_BUILD_ROOT%\qtbase\
          cd %_QT_BUILD_ROOT%
          set PATH=%_QT_BUILD_ROOT%\qtrepotools\bin;%_QT_BUILD_ROOT%\qtbase\bin;%_QT_BUILD_ROOT%\gnuwin32\bin;%PATH%
          set QMAKE_CXXFLAGS=/std:c++14
          REM See https://bugreports.qt.io/browse/QTBUG-71540 for Qt 5.15.2 build issues on Windows
          call %GITHUB_WORKSPACE%\Qt\configure.bat "QMAKE_CXXFLAGS+=/std:c++14" ^
            -c++std c++14 ^
            -release ^
            -nomake tests ^
            -nomake examples ^
            -qtnamespace QT ^
            -confirm-license ^
            -accessibility ^
            -opensource ^
            -platform win32-msvc ^
            -opengl desktop ^
            -prefix %_QT_BUILD_ROOT%\qtbase ^
            -skip qtdocgallery
          cd %_QT_BUILD_ROOT%
          C:\jom\jom.exe -j%NUMBER_OF_PROCESSORS%
          C:\jom\jom.exe -j%NUMBER_OF_PROCESSORS% install
      - name: Save Qt cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ github.job }}-qt-${{ hashFiles('msbuild_version', 'qt_version', 'cache_seed') }}
      - name: Restore GammaRay cache
        id: gamma-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/GammaRay
          key: ${{ github.job }}-gamma-${{ hashFiles('msbuild_version', 'qt_version', 'cache_seed') }}
      - name: Clone latest Qt-GammaRay
        if: steps.gamma-cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: KDAB/GammaRay
          path: ${{ github.workspace }}/GammaRay
          fetch-depth: 1
          submodules: recursive
      - name: Check GammaRay content
        if: steps.gamma-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          @echo on
          echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
          dir %GITHUB_WORKSPACE%
          dir %GITHUB_WORKSPACE%\GammaRay
      - name: Save GammaRay cache
        uses: actions/cache/save@v3
        with:
          path: ${{ github.workspace }}/GammaRay
          key: ${{ github.job }}-gamma-${{ hashFiles('msbuild_version', 'qt_version', 'cache_seed') }}
      - name: Build Qt GammaRay
        if: steps.gamma-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          echo GITHUB_WORKSPACE=%GITHUB_WORKSPACE%
          set _ROOT=%GITHUB_WORKSPACE%\Qt\build\${{ env.CI_QT_VERSION }}
          set PATH=%_ROOT%\qtrepotools\bin;%_ROOT%\qtbase\bin;%_ROOT%\gnuwin32\bin;%PATH%
          mkdir %GITHUB_WORKSPACE%\artifacts\
          mkdir %GITHUB_WORKSPACE%\GammaRay\build\
          cd %GITHUB_WORKSPACE%\GammaRay\build\
          cmake -G "NMake Makefiles" ^
            -S "%GITHUB_WORKSPACE%\GammaRay" ^
            -B "%GITHUB_WORKSPACE%\GammaRay\build" ^
            "-DCMAKE_BUILD_TYPE=Release" ^
            "-DCMAKE_PREFIX_PATH=%_ROOT%\qtbase\bin" ^
            "-DCMAKE_INSTALL_PREFIX=%GITHUB_WORKSPACE%\artifacts"
          nmake
          nmake install
      - name: Copy Qt DLLs
        shell: powershell
        run: |
          $qtPath = "$env:GITHUB_WORKSPACE\Qt\build\${{ env.CI_QT_VERSION }}"
          Write-Host "Qt Path: $qtPath"
          $env:Path = "$qtPath\qtbase\bin;" + $env:Path
          foreach ($_ in Get-ChildItem "$env:GITHUB_WORKSPACE\artifacts\bin" -Include *.exe,*.dll -Recurse) {
              & "$qtPath\qtbase\bin\windeployqt.exe" --release $_
          }
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Qt-GammaRay-x64-for-IDA-${{ env.IDA_VERSION }}-Qt-${{ env.CI_QT_VERSION }}.zip
          path: ${{ github.workspace }}/artifacts