name: Qt-GammaRay Builds
on: [push, pull_request, workflow_dispatch]

jobs:
  GammaRay-x64:
    runs-on: windows-latest
    env:
      CI_QT_VERSION: 5.15.2
      CI_SEED: 1234567890  # cache buster
    steps:
      - name: Enable Developer Command Prompt (Windows)
        uses: ilammy/msvc-dev-cmd@v1.12.1
        with:
            sdk: "10.0.22621.0"
            arch: amd64          
      - name: Install jom
        shell: powershell
        run: |
          Set-Location C:\
          Invoke-WebRequest 'http://download.qt.io/official_releases/jom/jom.zip' -OutFile .\jom.zip
          Expand-Archive .\jom.zip
          Remove-Item .\jom.zip
          Get-ChildItem $(pwd)
          Get-ChildItem .\jom
          Get-PSDrive
      - name: Check MSBuild and Qt
        run: |
          msbuild -version | Out-File -FilePath "$env:GITHUB_WORKSPACE\msbuild_version"
          Get-Content -Path "$env:GITHUB_WORKSPACE\msbuild_version"
          $env:CI_QT_VERSION | Out-File -FilePath "$env:GITHUB_WORKSPACE\qt_version"
          $env:CI_SEED | Out-File -FilePath "$env:GITHUB_WORKSPACE\cache_seed"          
      - name: Restore Qt cache
        id: qt-cache
        uses: actions/cache/restore@v3
        with:
          path: C:\Qt
          key: ${{ github.job }}-qt-${{ hashFiles('msbuild_version', 'qt_version', 'cache_seed') }}           
      - name: Clone Qt 5.15.2
        shell: cmd
        run: |
          @echo on
          C:
          mkdir C:\Qt\src\
          cd C:\Qt\src\
          git clone -b v5.15.2 https://code.qt.io/qt/qt5.git 5.15.2
          cd C:\Qt\src\5.15.2\
          git submodule update --init --recursive
      - name: Clone latest Qt-GammaRay
        if: steps.qt-cache.outputs.cache-hit != 'true'
        shell: cmd
        run: |
          @echo on
          C:
          cd C:\
          git clone https://github.com/KDAB/GammaRay.git
      - name: Save Qt cache
        if: steps.qt-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: C:\Qt
          key: ${{ github.job }}-qt-${{ hashFiles('msbuild_version', 'qt_version', 'cache_seed') }}              
      - name: Build Qt 5.15.2
        shell: cmd
        run: |
          @echo on
          C:
          set _ROOT=C:\Qt\build\5.15.2
          set PATH=%_ROOT%\qtrepotools\bin;%_ROOT%\qtbase\bin;%_ROOT%\gnuwin32\bin;%PATH%
          set _ROOT=
          mkdir C:\Qt\build\5.15.2\
          cd C:\Qt\build\5.15.2\
          call C:\Qt\src\5.15.2\configure.bat -release -nomake tests -nomake examples -qtnamespace QT -confirm-license -accessibility -opensource -platform win32-msvc -opengl desktop -prefix .\
          
          cd C:\Qt\build\5.15.2\
          C:\jom\jom.exe -j%NUMBER_OF_PROCESSORS%
          C:\jom\jom.exe -j%NUMBER_OF_PROCESSORS% install
          
          mkdir C:\artifacts\
          mkdir C:\GammaRay\build\
          cd C:\GammaRay\build\
          cmake -G "NMake Makefiles" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_PREFIX_PATH=C:\Qt\build\5.15.2\qtbase\bin" "-DCMAKE_INSTALL_PREFIX=C:\artifacts" ..
          nmake
          nmake install          
      - name: Copy Qt DLLs
        shell: powershell
        run: |
          $env:Path = "C:\Qt\build\5.15.2\qtbase\bin;" + $env:Path
          foreach ($_ in Get-ChildItem "C:\artifacts\bin" -Include *.exe,*.dll -Recurse) {
              & "C:\Qt\build\5.15.2\qtbase\bin\bin\windeployqt.exe" --release $_
          }
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qt-GammaRay-x64-for-ida.zip
          path: C:\artifacts